# minimal layout, agnostic to current terminal theme

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g focus-events on

set -g status-style "bg=default,fg=brightblack"
set -g status-justify absolute-centre
set -g status-left ""
set -g status-right ""

setw -g window-status-format " #W "
setw -g window-status-current-format "#[fg=white,bold] #W "
setw -g window-status-separator "#[fg=brightblack] • "

set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=white"

# keybindings

set -g prefix C-a
unbind C-b
bind C-a send-prefix

# leader + $       : rename session
# leader + d       : detach session
# leader + ,       : rename window
# ctrl + d         : delete pane/window

# leader + r       : reload config
# leader + v       : vertical split
# leader + s       : horizontal split
# leader + c       : new window
# leader + h/j/k/l : move panes
# shift + left     : move left window
# shift + right    : move right window

bind r source-file ~/.tmux.conf

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n S-Left previous-window
bind -n S-Right next-window
