brew "colima"
brew "docker"
brew "eza"
brew "fd"
brew "fzf"
brew "lazygit"
brew "micromamba"
brew "neovim"
brew "pure"
brew "ripgrep"
brew "tmux"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "arc"
cask "iterm2"
cask "mac-mouse-fix"
cask "swish"
cask "visual-studio-code"

tap "homebrew/cask-fonts"
cask "font-jetbrains-mono-nerd-font"

brew "mas"
mas "Tailscale", id: 1475387142
