brew "bat"
brew "colima"
brew "docker"
brew "eza"
brew "fd"
brew "fzf"
brew "helix"
brew "lazygit"
brew "micromamba"
brew "pure"
brew "ripgrep"
brew "tree"
brew "yazi"
brew "zellij"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

tap "homebrew/cask-fonts"
cask "font-roboto-mono-nerd-font"

cask "arc"
cask "iterm2"
cask "mac-mouse-fix"
cask "swish"
cask "visual-studio-code"

brew "mas"
mas "Tailscale", id: 1475387142
