theme = "catppuccin_mocha"

[editor]
line-number = "relative"
auto-pairs  = false  # annoying feature that isn't smart enough yet

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

# TODO: https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.f]
f = "file_picker"
F = "file_picker_in_current_directory"
g = ":pipe-to zellij run -c -d down -- hrf"  # live grep

[keys.normal.space]
f = "no_op"
F = "no_op"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
