theme = "catppuccin_mocha"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

