[language-server.ruff-lsp]
command = "micromamba"
args    = ["run", "-n", "lsp", "ruff-lsp"]

[language-server.pyright]
command = "micromamba"
args    = ["run", "-n", "lsp", "pyright-langserver", "--stdio"]

[[language]]
name             = "python"
language-servers = [ "ruff-lsp", "pyright" ]
formatter        = { command = "black", args = ["--quiet", "-"] }
auto-format      = true
