# NOTE: hx cannot be used as my editor because i can't dynamically
#       set the pythonPath for pyright with a conda env that is activated

[language-server.ruff-lsp]
command = "micromamba"
args    = [ "run", "-n", "lsp", "ruff-lsp" ]

[language-server.pyright]
command = "micromamba"
args    = [ "run", "-n", "lsp", "pyright-langserver", "--stdio" ]

[[language]]
name             = "python"
language-servers = [ "ruff-lsp", "pyright" ]
auto-format      = true
formatter        = { command = "micromamba", args = [ "run", "-n", "lsp", "ruff", "format", "-" ] }
